name: Workflow Time Report
decription: Workflow Time Report
inputs:
  create-issue:
    description: Whether to create ISSUE and LABEL
    required: true
    default: 'true'
outputs:
  markdown:
    description: Markdown Report
    value: ${{ steps.markdown.outputs.stdout }}
runs:
  using: composite
  steps:
    - name: Get current time
      id: current_time
      shell: bash
      run: echo "::set-output name=stdout::$(date '+%Y-%m-%d %H:%M:%S')"
      env:
        TZ: Asia/Tokyo
        GH_TOKEN: ${{ github.token }}

    - name: Create markdown
      id: markdown
      shell: bash
      run: |
        data=$(./report.sh "${{ github.repository }}")
        data="${data//$'\n'/\\n}"
        echo "::set-output name=stdout::$data"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Create ISSUE and LABEL
      shell: bash
      if: ${{ inputs.create-issue == 'true' }}
      run: |
        label_name='workflow-time-report'
        gh label create "$label_name" -R ${{ github.repository }} --description "workflow time report" --color E99695 -f
        body="${{ steps.markdown.outputs.stdout }}"
        gh issue create -R ${{ github.repository }} --label "$label_name" --body "$(echo -e $body)" --title "Workflow Time Report（${{ steps.current_time.outputs.stdout }}）"
      env:
        GH_TOKEN: ${{ github.token }}
