name: Workflow Time Report
decription: Workflow Time Report
inputs:
  label:
    description: Attached Label
    required: false
    default: workflow-time-report

runs:
  using: composite
  steps:
    - name: Get current time
      id: current_time
      shell: bash
      run: echo "::set-output name=stdout::$(date '+%Y-%m-%d %H:%M:%S')"
      env:
        TZ: Asia/Tokyo
        GH_TOKEN: ${{ github.token }}

    - name: Create markdown
      id: markdown
      shell: bash
      run: |
        data=$(bash report.sh "${{ github.repository }}")
        data="${data//$'\n'/\\n}"
        echo "::set-output name=stdout::$data"
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Create attached label
      shell: bash
      run: |
        gh label create "${{ inputs.label }}" -R ${{ github.repository }} --description "workflow time report" --color E99695
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Create report to ISSUE
      shell: bash
      run: |
        body="${{ steps.markdown.outputs.stdout }}"
        gh issue create -R ${{ github.repository }} --label ${{ inputs.label }} --body "$(echo -e $body)" --title "Workflow Time Report（${{ steps.current_time.outputs.stdout }}）"
      env:
        GH_TOKEN: ${{ github.token }}
