name: Workflow Time Report
author: MichinaoShimizu
description: Github Action that outputs Billable Time for each Workflow to ISSUE.
outputs:
  markdown:
    description: Markdown Report
    value: ${{ steps.markdown.outputs.stdout }}

runs:
  using: composite
  steps:
    - name: Generate markdown text
      id: markdown
      shell: bash
      run: |
        data=$(bash $GITHUB_ACTION_PATH/report.sh)
        data="${data//$'\n'/\\n}"
        echo "::set-output name=stdout::$data"
      env:
        GH_TOKEN: ${{ github.token }}
        TARGET_REPOSITORY: ${{ github.repository }}

    - name: Create issue and label
      shell: bash
      run: |
        label_name='workflow-time-report'
        gh label create "$label_name" -R ${{ github.repository }} --description "workflow time report" --color 000000 -f
        body="${{ steps.markdown.outputs.stdout }}"
        gh issue create -R ${{ github.repository }} --label "$label_name" --body "$(echo -e $body)" --title "Workflow Time Report"
      env:
        GH_TOKEN: ${{ github.token }}

branding:
  icon: "sun"
  color: "orange"
