
name: Shellcheck

on:
  pull_request:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check scripts with shellcheck
      run: |
        git diff origin/${GITHUB_BASE_REF}..origin/${GITHUB_HEAD_REF} \
          --diff-filter=AM \
          --name-only -- '*.sh' | while read script ; do \
              shellcheck $script || \
              touch error.$$ ; \
            done
        test ! -e error.$$
