
name: Shellcheck

on:
  pull_request:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: shellcheck
      uses: reviewdog/action-shellcheck@v1
      with:
        github_token: ${{ github.token }}
        reporter: github-pr-review # Change reporter.
        path: "." # Optional.
        pattern: "*.sh" # Optional.
        exclude: "./.git/*" # Optional.
        check_all_files_with_shebangs: "false"
