
name: Shellcheck

on:
  pull_request:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check scripts with shellcheck
      # env:
      #   EXCLUDE_OPTS: SC2086,SC2001
      run: shellcheck
        shellcheck ${EXCLUDE_OPTS:+-e ${EXCLUDE_OPTS}} $script -f diff | git apply
