
name: Shellcheck

on:
  pull_request:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ github.token }}
          reporter: "github-pr-review"
          level: "warning"
          path: "."
          pattern: "*.sh"
          fail_on_error: "true"
          exclude: "./.git/*"
