name: Test Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "action.yml"
      - "**.sh"

jobs:
  reporting:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3
      - uses: ./
